on:
    # Workflows check plugin Jeedom
    push:
      branches:
        - beta
    pull_request:
      branches:
        - beta
  name : 'Full Workflows Plugin Jeedom'
  
  jobs:
    plugin:
      uses: https://github.com/jeedom/workflows/.github/workflows/plugin.yml@main